### ISSUE TITLE
Cannot build 

### ISSUE THREAD

**Issue by zeusmoss** [niklr/angular-material-datatransfer#9]
Running npm start got error:

'webpack-dev-server' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-material-datatransfer@2.1.1 server: `webpack-dev-server --open --inline --progress --port 8080`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-material-datatransfer@2.1.1 server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by niklr** [comment]
Did you follow those steps?

In order to build Angular Material Datatransfer, ensure that you have Git and Node.js installed.

Clone a copy of the repo:

`git clone https://github.com/niklr/angular-material-datatransfer.git`

Change to the angular-material-datatransfer directory:

`cd angular-material-datatransfer`

Install dependencies:

`npm install`

**Comment by zeusmoss** [comment]
yes i have git and node.js installed. previously i used the vs code to install and build also tried few of these too clean, clean-install , clean-start. didn't help. 

**I retired now everything using git cmd works fine now.**

do you have a module/plugin of this so i can integrate on existing project? because i don't see it on the npm to install it.

**Comment by niklr** [comment]
I just created a npm package, would be nice if you can test it.

https://www.npmjs.com/package/angular-material-datatransfer

**Comment by zeusmoss** [comment]
sure

**Comment by niklr** [comment]
With recent updates on Angular side it is now easier to create reusable libraries. To add this library as a module in an existing Angular project please consider the steps described [here](https://github.com/niklr/angular-material-datatransfer/tree/master/projects/amd-lib).

The corresponding npm package:
https://www.npmjs.com/package/angular-material-datatransfer-lib
